WebInt-Backend2-master/Backend2/Controllers/ColculationController.cs
using System;
using Backend2.Models;
using Backend2.Services;
using Microsoft.AspNetCore.Mvc;

namespace Backend2.Controllers
{
    public class ColculationController : Controller
    {
        private readonly ICalculation calculation;

        public ColculationController(ICalculation calculation)
        {
            this.calculation = calculation;
        }

        public ActionResult Manual()
        {
            if (this.Request.Method.Equals("POST", StringComparison.OrdinalIgnoreCase))
            {
                string result = "";
                string num1 = this.Request.Form["Num1"];
                if (String.IsNullOrEmpty(num1))
                {
                    this.ViewBag.Error1 = "first number is required";
                    return this.View();
                }
                int saveNum1 = int.Parse(num1);

                string num2 = this.Request.Form["Num2"];
                if (String.IsNullOrEmpty(num2))
                {
                    this.ViewBag.Error2 = "Second number is required";
                    return this.View();
                }
                String Op = this.Request.Form["Op"];

                if (Op == "/" && num2 == "0")
                {
                    this.ViewBag.Error3 = "Can't divide by Zero";
                    return this.View();
                }

                int saveNum2 = int.Parse(num2);



                if (Op == "+")
                {
                    result = calculation.Sum(saveNum1, saveNum2) + "";
                }
                else if (Op == "-")
                {
                    result = calculation.Sub(saveNum1, saveNum2) + "";
                }
                else if (Op == "/")
                {
                    result = calculation.Division(saveNum1, saveNum2) + "";
                }
                else if (Op == "*")
                {
                    result = calculation.Multiplication(saveNum1, saveNum2) + "";
                }

                var resultModel = new ColculationModel()
                {
                    firstNum = saveNum1,
                    secondNum = saveNum2,
                    Result = result
                };
                return this.View("Result", resultModel);
            }

            return this.View();
        }
        [HttpGet]
        public ActionResult ManualWithSeparateHandlers()
        {
            return this.View();
        }

        [HttpPost, ActionName("ManualWithSeparateHandlers")]
        [ValidateAntiForgeryToken]
        public ActionResult ManualWithSeparateHandlersConfirm()
        {


            string result = "";
            string num1 = this.Request.Form["Num1"];
            if (String.IsNullOrEmpty(num1))
            {
                this.ViewBag.Error1 = "first number is required";
                return this.View();
            }
            int saveNum1 = int.Parse(num1);

            string num2 = this.Request.Form["Num2"];
            if (String.IsNullOrEmpty(num2))
            {
                this.ViewBag.Error2 = "Second number is required";
                return this.View();
            }
            String Op = this.Request.Form["Op"];

            if (Op == "/" && num2 == "0")
            {
                this.ViewBag.Error3 = "Can't divide by Zero";
                return this.View();
            }

            int saveNum2 = int.Parse(num2);



            if (Op == "+")
            {
                result = calculation.Sum(saveNum1, saveNum2) + "";
            }
            else if (Op == "-")
            {
                result = calculation.Sub(saveNum1, saveNum2) + "";
            }
            else if (Op == "/")
            {
                result = calculation.Division(saveNum1, saveNum2) + "";
            }
            else if (Op == "*")
            {
                result = calculation.Multiplication(saveNum1, saveNum2) + "";
            }


            var resultModel = new ColculationModel()
            {
                firstNum = saveNum1,
                secondNum = saveNum2,
                Result = result
            };
            return this.View("Result", resultModel);
        }


        public ActionResult ModelBindingInParameters()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ModelBindingInParameters(string Num1, string Num2)
        {
            string result = "";
            if (String.IsNullOrEmpty(Num1))
            {
                this.ViewBag.Error1 = "first number is required";
                return this.View();
            }
            int saveNum1 = int.Parse(Num1);


            if (String.IsNullOrEmpty(Num2))
            {
                this.ViewBag.Error2 = "Second number is required";
                return this.View();
            }


            String Op = this.Request.Form["Op"];
            if (Op == "/" && Num2 == "0")
            {
                this.ViewBag.Error3 = "Can't divide by Zero";
                return this.View();
            }

            int saveNum2 = int.Parse(Num2);



            if (Op == "+")
            {
                result = calculation.Sum(saveNum1, saveNum2) + "";
            }
            else if (Op == "-")
            {
                result = calculation.Sub(saveNum1, saveNum2) + "";
            }
            else if (Op == "/")
            {
                result = calculation.Division(saveNum1, saveNum2) + "";
            }
            else if (Op == "*")
            {
                result = calculation.Multiplication(saveNum1, saveNum2) + "";
            }


            var resultModel = new ColculationModel()
            {
                firstNum = saveNum1,
                secondNum = saveNum2,
                Result = result
            };
            return this.View("Result", resultModel);
        }










        public ActionResult ModelBindingInSeparateModel()
        {
            return this.View(new CalculateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ModelBindingInSeparateModel(CalculateViewModel model)
        {
            string result = "";
            string firstNum = this.Request.Form["firstNum"];
            string secondNum = this.Request.Form["secondNum"];

            if (this.ModelState.IsValid)
            {
               
                int saveNum1 = int.Parse(firstNum);
                String Op = this.Request.Form["Op"];
                if (Op == "/" && secondNum == "0")
                {
                    this.ModelState.AddModelError("secondNum", "Cant divide by Zero");
                    return this.View(model);
                }

                int saveNum2 = int.Parse(secondNum);



                if (Op == "+")
                {
                    result = calculation.Sum(saveNum1, saveNum2) + "";
                }
                else if (Op == "-")
                {
                    result = calculation.Sub(saveNum1, saveNum2) + "";
                }
                else if (Op == "/")
                {
                    result = calculation.Division(saveNum1, saveNum2) + "";
                }
                else if (Op == "*")
                {
                    result = calculation.Multiplication(saveNum1, saveNum2) + "";
                }


                var resultModel = new ColculationModel()
                {
                    firstNum = saveNum1,
                    secondNum = saveNum2,
                    Result = result
                };
                return this.View("Result", resultModel);



            }
            return this.View(model);

        }
    }
}

WebInt-Backend2-master/Backend2/Views/Colculation/Manual.cshtml
@model dynamic
@{
    ViewBag.Title = "Calculator";
}

    <h2>Calculator</h2>

            <form asp-controller="Colculation" asp-action="Manual">
                <div class="form-group form-inline">
                    <div class="row">

                        @if (ViewBag.Error1 == null && ViewBag.Error2 == null && ViewBag.Error3 == null)
                        {
                            <input class="form-control" name="Num1" type="text" />
                            <select name="Op" class="form-control">
                                <option selected>+</option>
                                <option>-</option>
                                <option>*</option>
                                <option>/</option>
                            </select>


                            <input class="form-control" name="Num2" type="text" />

                        }
                        else if (ViewBag.Error1 != null)
                        {
                            <input class="form-control" name="Num1" type="text" />
                            <select name="Op" class="form-control">
                                <option selected>+</option>
                                <option>-</option>
                                <option>*</option>
                                <option>/</option>
                            </select>
                            <input class="form-control" name="Num2" type="text" />
                            <span class="field-validation-error">@ViewBag.Error1</span>
                        }
                        else if (ViewBag.Error2 != null)
                        {
                            <input class="form-control" name="Num1" type="text" />
                            <select name="Op" class="form-control">
                                <option selected>+</option>
                                <option>-</option>
                                <option>*</option>
                                <option>/</option>
                            </select>
                            <input class="form-control" name="Num2" type="text" />
                            <span class="field-validation-error">@ViewBag.Error2</span>
                        }
                        else if (ViewBag.Error3 != null )
                        {
                            <input class="form-control" name="Num1" type="text" />
                            <select name="Op" class="form-control">
                                <option selected>+</option>
                                <option>-</option>
                                <option>*</option>
                                <option>/</option>
                            </select>
                            <input class="form-control" name="Num2" type="text" />
                            <span class="field-validation-error">@ViewBag.Error3</span>
                        }
                        <button type="submit" class="btn btn-primary"> Calculate</button>
                    </div>
                    </div>
            </form>

WebInt-Backend2-master/Backend2/Views/Colculation/ManualWithSeparateHandlers.cshtml
@model dynamic
@{
    ViewBag.Title = "Calculator";
}

<h2>Calculator</h2>

<form asp-controller="Colculation" asp-action="ManualWithSeparateHandlers">
    <div class="form-group form-inline">
        <div class="row">

            @if (ViewBag.Error1 == null && ViewBag.Error2 == null && ViewBag.Error3 == null)
            {
                <input class="form-control" name="Num1" type="text" />
                <select name="Op" class="form-control">
                    <option selected>+</option>
                    <option>-</option>
                    <option>*</option>
                    <option>/</option>
                </select>


                <input class="form-control" name="Num2" type="text" />

            }
            else if (ViewBag.Error1 != null)
            {
                <input class="form-control" name="Num1" type="text" />
                <select name="Op" class="form-control">
                    <option selected>+</option>
                    <option>-</option>
                    <option>*</option>
                    <option>/</option>
                </select>
                <input class="form-control" name="Num2" type="text" />
                <span class="field-validation-error">@ViewBag.Error1</span>
            }
            else if (ViewBag.Error2 != null)
            {
                <input class="form-control" name="Num1" type="text" />
                <select name="Op" class="form-control">
                    <option selected>+</option>
                    <option>-</option>
                    <option>*</option>
                    <option>/</option>
                </select>
                <input class="form-control" name="Num2" type="text" />
                <span class="field-validation-error">@ViewBag.Error2</span>
            }
            else if (ViewBag.Error3 != null)
            {
                <input class="form-control" name="Num1" type="text" />
                <select name="Op" class="form-control">
                    <option selected>+</option>
                    <option>-</option>
                    <option>*</option>
                    <option>/</option>
                </select>
                <input class="form-control" name="Num2" type="text" />
                <span class="field-validation-error">@ViewBag.Error3</span>
            }
            <button type="submit" class="btn btn-primary"> Calculate</button>
        </div>
    </div>
</form>

WebInt-Backend2-master/Backend2/Views/Colculation/ModelBindingInParameters.cshtml
@model Backend2.Models.CalculateViewModel
@{
    ViewBag.Title = "Calculator";
}

<h2>Calculator</h2>

<form asp-controller="Colculation" asp-action="ModelBindingInSeparateModel">
    <div class="form-group form-inline">
        <div class="row">
            <input class="form-control" asp-for="firstNum" type="text" />
            <span class="field-validation-error" asp-validation-for="firstNum"></span>
            <select name="Op" class="form-control">
                <option selected>+</option>
                <option>-</option>
                <option>*</option>
                <option>/</option>
            </select>
            <input class="form-control" asp-for="secondNum" type="text" />
            <span class="field-validation-error" asp-validation-for="secondNum"></span>
            <button type="submit" class="btn btn-primary"> Calculate</button>
        </div>
    </div>
</form>

WebInt-Backend2-master/Backend2/Views/Colculation/ModelBindingInSeparateModel.cshtml
@model dynamic
@{
    ViewBag.Title = "Calculator";
}

<h2>Calculator</h2>

<form asp-controller="Colculation" asp-action="ModelBindingInParameters">
    <div class="form-group form-inline">
        <div class="row">

            @if (ViewBag.Error1 == null && ViewBag.Error2 == null && ViewBag.Error3 == null)
            {
                <input class="form-control" name="Num1" type="text" />
                <select name="Op" class="form-control">
                    <option selected>+</option>
                    <option>-</option>
                    <option>*</option>
                    <option>/</option>
                </select>


                <input class="form-control" name="Num2" type="text" />

            }
            else if (ViewBag.Error1 != null)
            {
                <input class="form-control" name="Num1" type="text" />
                <select name="Op" class="form-control">
                    <option selected>+</option>
                    <option>-</option>
                    <option>*</option>
                    <option>/</option>
                </select>
                <input class="form-control" name="Num2" type="text" />
                <span class="field-validation-error">@ViewBag.Error1</span>
            }
            else if (ViewBag.Error2 != null)
            {
                <input class="form-control" name="Num1" type="text" />
                <select name="Op" class="form-control">
                    <option selected>+</option>
                    <option>-</option>
                    <option>*</option>
                    <option>/</option>
                </select>
                <input class="form-control" name="Num2" type="text" />
                <span class="field-validation-error">@ViewBag.Error2</span>
            }
            else if (ViewBag.Error3 != null)
            {
                <input class="form-control" name="Num1" type="text" />
                <select name="Op" class="form-control">
                    <option selected>+</option>
                    <option>-</option>
                    <option>*</option>
                    <option>/</option>
                </select>
                <input class="form-control" name="Num2" type="text" />
                <span class="field-validation-error">@ViewBag.Error3</span>
            }
            <button type="submit" class="btn btn-primary"> Calculate</button>
        </div>
    </div>
</form>

WebInt-Backend2-master/Backend2/Views/Colculation/Result.cshtml
@model Backend2.Models.ColculationModel
@{
    ViewBag.Title = "Calculator";
}

<h2>Calculator</h2>

<form asp-action="Manual">
    <div class="form-group form-inline">
        <div class="row">

                <input class="form-control" name="Num1" type="text"  value="@Model.firstNum"/>
                <select name="Op" class="form-control">
                    <option selected>+</option>
                    <option>-</option>
                    <option>*</option>
                    <option>/</option>
                </select>
                <input class="form-control" name="Num2" type="text" value="@Model.secondNum" />

            <p class="form-group"> = @Model.Result</p>
        </div>
    </div>
</form>